#!/usr/bin/env ruby

require "z3"
require_relative "rx"
require_relative "regexp_solver"

RegexpCrosswordSolver.new(
  [
    RX.c("A") | RX.c("C"),
    RX.c("B"),
  ],
  [
    RX.c("A").optional + RX.c("B").optional,
  ]
).solve
