#!/usr/bin/env ruby

require "z3"
require_relative "rx"
require_relative "regexp_solver"

RegexpCrosswordSolver.new(
  [
    RX.c("A"),
    RX.c("A") + RX.c("B").star,
  ],
  [
    RX.c("A").star,
  ]
).solve
